dist: trusty
sudo: required
language: rust
rust:
  - stable

env:
  global:
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - TNS_ADMIN=$ORACLE_HOME/network/admin
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib
    - DATABASE_VERSION=11.2.0.1
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/Riga' #Needed as a client parameter
    - TZ='Europe/Riga'       #Needed as a DB Server parameter
    - ODPIC_TEST_CONNECT_STRING=

install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - .travis/setup_accounts.sh

script:
  - cargo test --all-features -- --nocapture
